In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

arr_rev = arr[::-1]
print(arr_rev)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [8]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print(n_array)
#sum up diagonal arrays
diag_sum = np.trace(n_array)
print("Sum of diag elements:")
print(diag_sum)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diag elements:
176


In [10]:
#eigen values of array
eig = np.linalg.eig(n_array)
print(eig)

EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
